# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-02 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_image'),
    ]

    operations = [
        migrations.RenameModel('Item', 'Paintings')
    ]
