# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-28 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='charity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.CharityDesign'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='graphics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.GraphicDesign'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='paintings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Paintings'),
        ),
    ]
