# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-30 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20160929_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='user_profile',
            field=models.TextField(null=True),
        ),
    ]
