# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-18 00:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('evil_dog_image', '0005_charitydesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintings',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 18, 0, 24, 16, 686924, tzinfo=utc), verbose_name='Uploaded at'),
            preserve_default=False,
        ),
    ]
