# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-28 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evil_dog_image', '0008_auto_20160928_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_user', models.CharField(max_length=200)),
                ('likes_url', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded at')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              to='evil_dog_image.CharityDesign')),
                ('graphics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               to='evil_dog_image.GraphicDesign')),
                ('paintings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                to='evil_dog_image.Paintings')),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
    ]
