# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-29 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evil_dog_image', '0012_auto_20160928_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='charity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='evil_dog_image.CharityDesign', verbose_name='charity'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='graphics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='evil_dog_image.GraphicDesign', verbose_name='graphic'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='paintings',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='evil_dog_image.Paintings', verbose_name='paintings'),
        ),
    ]
